const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '../../main/resources/static');
const html = fs.readFileSync(path.join(root, 'novel-detail.html'), 'utf8');
const newHtml = fs.readFileSync(path.join(root, 'novel-detail-new.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'js/novel-detail.js'), 'utf8');
const shellCss = fs.readFileSync(path.join(root, 'studio/css/workbench-shell.css'), 'utf8');
const previewCss = fs.readFileSync(path.join(root, 'studio/css/workbenches-new.css'), 'utf8');

assert(html.includes('class="studio-theme studio-detail-page"'));
assert(html.includes('class="toolbar workspace-header"'));
assert(html.includes('class="detail-layout workspace-shell"'));
assert.match(shellCss, /\.studio-detail-page \.workspace-header > div:first-child\s*\{[\s\S]*?min-width:\s*0/, 'detail title column should allow single-line ellipsis');
assert.match(shellCss, /\.studio-detail-page \.workspace-header h1\s*\{[\s\S]*?white-space:\s*nowrap/, 'detail title should stay on one line');
assert.match(shellCss, /\.studio-detail-page \.workspace-header h1\s*\{[\s\S]*?max-width:\s*none/, 'detail title should not be constrained to a short character width');
assert.match(shellCss, /\.studio-detail-page \.workspace-header h1\s*\{[\s\S]*?text-overflow:\s*clip/, 'detail title should remain fully visible instead of ellipsis');
assert(html.includes('id="visualStyleEra"'));
assert(html.includes('id="saveVisualStyleBtn"'));
assert(html.includes('id="generateVisualStyleBtn"'));
assert(html.includes('class="visual-style-section"'));
assert(html.includes('class="visual-style-summary"'));
assert(html.includes('class="visual-style-toggle"'));
assert(script.includes('class="storyboard-card-toggle"') || script.includes('storyboard-card-head'));
assert.match(script, /card\.open\s*=\s*index\s*===\s*0/, 'storyboard cards should start compact with only the first scene expanded');
assert(script.includes('class="asset-card-toggle"'));
assert(script.includes('/visual-style'));
assert(script.includes('saveVisualStyle'));
assert(script.includes('generateVisualStyle'));
assert(script.includes('data-field="shotPlan"'));
assert(script.includes('isValidShotPlan'));
assert(script.includes('时长 0:00-0:05'));
assert(script.includes('镜头脚本'));
assert(script.includes('const currentActiveId = activeChapter && getChapterId(activeChapter);'));
assert(script.includes('currentActiveId === getChapterId(nextActive)'));
assert(script.includes('getChapterNumber(activeChapter) === getChapterNumber(nextActive)'));
assert(script.includes('activeStoryboard && !assetTabPanel.hidden'));
assert(script.includes('let loadedStoryboardChapterNum = null;'));
assert(script.includes('const sameStoryboardChapter = loadedStoryboardChapterNum === String(chapterNum)'));
assert(script.includes('if (!sameStoryboardChapter || !activeStoryboard)'));
assert(script.includes('novelTitle.title = novelTitle.textContent'), 'full novel title should remain available on hover');
assert(script.includes("document.querySelector('.workbench-context h1')"), 'workspace header should receive the loaded title');
assert(script.includes("localStorage.setItem('mirror:videoContext'"), 'video navigation should persist the active chapter context');
assert(script.includes("workspaceTitle.textContent = '加载完成'"), 'workspace header should show the completed loading state');
assert(script.includes("novelTitle.textContent = '加载完成'"), 'missing novel id should use the completed loading title');
assert.match(newHtml, /id="readerEntryState"/);
assert.match(newHtml, /id="readerImportDialog"[^>]*hidden/);
assert.match(newHtml, /id="readerImportFile"[^>]*accept="\.txt,\.docx,text\/plain,application\/vnd\.openxmlformats-officedocument\.wordprocessingml\.document"/);
assert.match(newHtml, /id="readerImportSubmitBtn"/);
assert.match(newHtml, /id="readerHistoryBtn"/);
assert.match(previewCss, /\.new-workbench-page \.reader-import-dialog\[hidden\]\s*\{\s*display:\s*none/);
assert.match(previewCss, /\.reader-workspace \.chapter-nav button:not\(\.active\)\s*\{[^}]*background:\s*#fffdf9/, 'inactive chapter buttons should use a light background');
assert.match(previewCss, /\.reader-workspace \.chapter-nav button\.active\s*\{[^}]*background:\s*var\(--new-teal\)/, 'the selected chapter button should use the primary green background');
assert(script.includes("fetch('/api/novel/import', {method: 'POST', body: formData})"));
assert(script.includes("localStorage.setItem('mirror:selectedNovelId', String(result.novelId))"));
assert(script.includes('window.location.href = `/novel-detail-new.html?novelId=${encodeURIComponent(result.novelId)}`'));
assert(script.includes("generationStatus.textContent = '请选择或导入一部小说后开始创作。'"));

console.log('novel-detail visual-style checks passed');
