const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '../../main/resources/static');
const html = fs.readFileSync(path.join(root, 'video-generation.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'js/video-generation.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css/outline.css'), 'utf8');

assert(html.includes('id="sceneList"'));
assert(html.includes('分镜视频生成'));
assert(html.includes('class="studio-theme studio-video-page video-generation-body"'));
assert(html.includes('class="toolbar workspace-header"'));
assert(html.includes('id="pageSummary" class="asset-meta"></p>'));
assert(html.includes('请先在历史作品中选择小说，再继续视频生成。'));
assert(!html.includes('正在加载当前章节'));
assert(!html.includes('正在读取分镜脚本'));
assert(/class="video-scene-list workspace-shell(?: video-output-console)?"/.test(html));
assert(script.includes('/video-tasks'));
assert(script.includes("setStatus('请先选择小说', true)"));
assert(script.includes('data-action="generate-video"'));
assert(script.includes('data-field="resolution"'));
assert(script.includes('resolution'));
assert(script.includes('768P'));
assert(script.includes('720P'));
assert(script.includes('1080P'));
assert(script.includes('2K'));
assert(script.includes('JSON.stringify({sceneId: scene.id, firstFrameId, promptOverride, resolution})'));
assert(script.includes('video.resolution || \'未知分辨率\''));
assert(script.includes('data-action="generate-first-frame"'));
assert(script.includes('data-action="upload-first-frame"'));
assert(script.includes('data-action="upload-video"'));
assert(script.includes('const firstFrameButton = card.querySelector(\'[data-action="generate-first-frame"]\')'));
assert(!script.includes('const generateFirstFrame = card.querySelector'));
assert(script.includes('data-role="first-frame-list"'));
assert(script.includes('/first-frame-tasks'));
assert(script.includes('/first-frames'));
assert(script.includes('/first-frames/upload'));
assert(script.includes('/api/first-frame-tasks/${encodeURIComponent(taskId)}'));
assert(script.includes('请先选择首帧'));
assert(script.includes('firstFrameId'));
assert(script.includes('data-action="delete-first-frame"'));
assert(html.includes('id="firstFramePreviewDialog"'));
assert(script.includes('单击缩略图选择，双击查看大图'));
assert(script.includes('function openFirstFramePreview(frame)'));
assert(script.includes('function closeFirstFramePreview()'));
assert(script.includes("button.addEventListener('dblclick'"));
assert(script.includes('previewDialog.showModal()'));
assert(script.includes('/videos'));
assert(script.includes('/videos/upload'));
assert(script.includes('/storyboard-videos/'));
assert(script.includes('FormData'));
assert(script.includes('手动上传'));
assert(script.includes('AI 生成'));
assert(script.includes('data-action="delete-video"'));
assert(script.includes('参考资产'));
assert(script.includes('data-action="remove-reference-asset"'));
assert(script.includes('class="video-reference-media"'));
assert(script.includes('aria-label="移除${escapeHtml(ref.label)}参考资产"'));
assert(script.includes('function removeReferenceAsset(card, scene, assetId, assetRole)'));
assert(script.includes('assetRole=${encodeURIComponent(assetRole)}'));
assert(script.includes('仅移除该资产在当前分镜中的引用'));
assert(script.includes('/safety-rewrite'));
assert(script.includes('安全改写后重试'));
assert(script.includes('正在生成视频'));
assert(script.includes('分镜首帧'));
assert(script.includes('failedTaskId'));
assert(script.includes('/api/video-tasks/${encodeURIComponent(failedTaskId)}/retry'));
assert(script.includes('scene.shotPlan'));
assert(script.includes('<h3>分镜脚本</h3>'));
assert(!script.includes('<dt>镜头脚本</dt>'));
assert(!script.includes('暂无镜头脚本'));
assert(script.includes('class="video-scene-workspace"'));
assert(script.includes('class="video-script-panel"'));
assert(script.includes('class="video-assets-panel"'));
assert(script.includes('class="video-control-panel video-stage-operations"'));
assert(script.includes('class="video-primary-actions"'));
assert(script.includes('video-production-stage'));
assert(script.includes('class="video-stage-rail"'));
assert(script.includes('class="video-stage-canvas"'));
assert(script.includes('class="video-control-panel video-stage-operations"'));
assert(script.includes('class="video-output-dock"'));
assert(script.includes("quickNav.className = 'video-scene-quick-nav'"));
assert(script.includes('function renderSceneQuickNav'));
assert(script.includes("card.addEventListener('toggle'"));
assert(script.includes('01 / 准备首帧'));
assert(script.includes('02 / 生成视频'));
assert(script.includes("stageHost.id = 'video-stage-host'"));
assert(script.includes('function renderActiveScene'));
assert(script.includes('stageHost.replaceChildren(entry.card)'));
assert(!script.includes('entry.card.scrollIntoView'));
assert(script.includes('const scrollTop = window.scrollY;'));
assert(script.includes('window.scrollTo(0, scrollTop)'));
assert(script.includes('window.setTimeout(() => window.scrollTo(0, scrollTop), 0)'));
assert(css.includes('Responsive containment for the production-stage action rail'));
assert(css.includes('.studio-theme.video-generation-body .video-stage-operations .video-primary-actions > button'));
assert(css.includes('Final layout guard: control actions occupy the second row'));

console.log('video-generation page checks passed');
